"""Local-side tooling to drive a Kaggle script-kernel run via the `kaggle`
CLI: push the kernel, poll until it finishes, and pull its output back.
Wraps subprocess calls to the CLI rather than talking to Kaggle's API
directly, since `kaggle` is already the credentialed, working entry point
on this machine (see docs/implementation-plans/2026-08-20-stage2-kaggle-redo-design.md).

The pushed kernel is a script-kernel (kernel_type: "script"), not a
notebook -- its content is generated by render_kernel_script() with the
target repo commit and entrypoint module baked in as literals, rather than
relying on Kaggle's environment-variable support (not verified for this
project's use case)."""
import json
import subprocess
import time
from pathlib import Path

TERMINAL_STATUSES = {"complete", "error", "cancel_acknowledged"}

KERNEL_SCRIPT_TEMPLATE = '''\
"""Kaggle script-kernel entrypoint, generated by kaggle_runner.orchestrate.push().
Not run locally, not imported by the rest of this project."""
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/SikioN/lifelong-agent.git"
REPO_COMMIT = "{repo_commit}"
ENTRYPOINT = "{entrypoint}"


def main() -> None:
    # Clear any stale HuggingFace Hub cache/lock files left over from a
    # previous kernel version on this instance before doing anything else
    # -- rules out a corrupted cache or a stuck lock file as a contributor
    # to the weight-loading hang seen on earlier runs. Kaggle instances are
    # ephemeral, so this just means a fresh download, nothing is lost.
    shutil.rmtree(Path.home() / ".cache" / "huggingface", ignore_errors=True)

    subprocess.run(["git", "clone", REPO_URL, "repo"], check=True)
    subprocess.run(["git", "-C", "repo", "checkout", REPO_COMMIT], check=True)
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "-r", "repo/requirements.txt"],
        check=True,
    )
    # This project's code only ever targets one GPU (agent/policy.py's
    # _select_device() picks plain "cuda" = device 0). On a T4x2 Kaggle
    # instance, weight loading hung indefinitely (confirmed twice,
    # reproducibly, at the same "Materializing param=..." step) when both
    # GPUs were visible to the process -- restricting visibility to a
    # single GPU works around whatever PyTorch/transformers multi-GPU
    # coordination issue causes that.
    env = dict(os.environ, CUDA_VISIBLE_DEVICES="0")
    subprocess.run([sys.executable, "-m", ENTRYPOINT], check=True, cwd="repo", env=env)

    # Kaggle captures whatever's in the working directory as kernel output --
    # copy the entrypoint's results here explicitly rather than relying on
    # where it happened to write them relative to the cloned repo.
    for output_dir_name in ("calibration_output", "diagnostic_output"):
        src = Path("repo/experiments") / output_dir_name
        if src.exists():
            shutil.copytree(src, output_dir_name, dirs_exist_ok=True)


if __name__ == "__main__":
    main()
'''


def render_kernel_script(repo_commit: str, entrypoint: str) -> str:
    """Fills in the Kaggle script-kernel template with a pinned commit and
    the module to run -- baked in as literals so the pushed kernel doesn't
    depend on Kaggle's environment-variable support."""
    return KERNEL_SCRIPT_TEMPLATE.format(repo_commit=repo_commit, entrypoint=entrypoint)


def render_kernel_notebook(repo_commit: str, entrypoint: str) -> str:
    """Wraps render_kernel_script()'s Python source into a minimal
    single-cell Jupyter notebook (nbformat 4). Same content, same
    reviewed logic as the script kernel -- this is only a different
    container format for Kaggle's notebook-kernel UI, not new logic
    living in a hand-edited notebook."""
    script = render_kernel_script(repo_commit, entrypoint)
    notebook = {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": script.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1)


def push(kernel_dir: Path, repo_commit: str, entrypoint: str) -> str:
    """Renders the kernel payload for (repo_commit, entrypoint) in
    whichever format kernel-metadata.json's code_file specifies (.py for
    a script kernel, .ipynb for a notebook kernel -- same underlying
    logic either way), writes it into kernel_dir, pushes via the kaggle
    CLI, and returns the kernel id read from kernel-metadata.json."""
    metadata = json.loads((kernel_dir / "kernel-metadata.json").read_text())
    code_file = kernel_dir / metadata["code_file"]
    if code_file.suffix == ".ipynb":
        content = render_kernel_notebook(repo_commit, entrypoint)
    else:
        content = render_kernel_script(repo_commit, entrypoint)
    code_file.write_text(content)
    subprocess.run(["kaggle", "kernels", "push", "-p", str(kernel_dir)], check=True)
    return metadata["id"]


def get_status(kernel_id: str) -> str:
    """Returns the kernel's current run status, normalized to a bare
    lowercase word ("running", "complete", "error", ...).

    Confirmed against the real CLI (2026-08-20): the raw quoted value is
    NOT a bare word as originally assumed -- it's an enum repr like
    `KernelWorkerStatus.RUNNING`, e.g. the full line is
    `{kernel_id} has status "KernelWorkerStatus.RUNNING"`. Strip the enum
    class prefix and lowercase it so callers (and TERMINAL_STATUSES) don't
    need to know about that wrapping."""
    result = subprocess.run(
        ["kaggle", "kernels", "status", kernel_id],
        check=True,
        capture_output=True,
        text=True,
    )
    raw_status = result.stdout.split('"')[1]
    return raw_status.rsplit(".", 1)[-1].lower()


def wait_for_completion(kernel_id: str, poll_interval_s: float = 30.0, timeout_s: float = 3600.0) -> str:
    """Polls get_status until it reaches a terminal status or timeout_s
    elapses. Returns the terminal status; raises TimeoutError on timeout."""
    start = time.monotonic()
    while True:
        status = get_status(kernel_id)
        if status in TERMINAL_STATUSES:
            return status
        if time.monotonic() - start > timeout_s:
            raise TimeoutError(
                f"kernel {kernel_id} did not finish within {timeout_s}s (last status: {status})"
            )
        time.sleep(poll_interval_s)


def pull_output(kernel_id: str, dest_dir: Path) -> Path:
    """Downloads the kernel's output files into dest_dir, returns dest_dir."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["kaggle", "kernels", "output", kernel_id, "-p", str(dest_dir)],
        check=True,
    )
    return dest_dir
