"""Local-side tooling to drive a Kaggle script-kernel run via the `kaggle`
CLI: push the kernel, poll until it finishes, and pull its output back.
Wraps subprocess calls to the CLI rather than talking to Kaggle's API
directly, since `kaggle` is already the credentialed, working entry point
on this machine (see docs/implementation-plans/2026-08-20-stage2-kaggle-redo-design.md).

The pushed kernel can be either a script-kernel (kernel_type: "script",
code_file ending in .py) or a notebook-kernel (kernel_type: "notebook",
code_file ending in .ipynb) -- push() reads kernel-metadata.json's
code_file suffix and dispatches to render_kernel_script() or
render_kernel_notebook() accordingly. Both render the same underlying
logic (repo commit and entrypoint module baked in as literals, rather
than relying on Kaggle's environment-variable support); the notebook
form is just a different container for that same content. Notebook
support was added on top of the original script-only design because the
human partner preferred a Colab-adjacent notebook workflow (see git log
"Add notebook-kernel support to orchestrate.py")."""
import json
import subprocess
import time
from pathlib import Path

TERMINAL_STATUSES = {"complete", "error", "cancel_acknowledged"}

KERNEL_SCRIPT_TEMPLATE = '''\
"""Kaggle script-kernel entrypoint, generated by kaggle_runner.orchestrate.push().
Not run locally, not imported by the rest of this project."""
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO_URL = "https://github.com/SikioN/lifelong-agent.git"
REPO_COMMIT = "{repo_commit}"
ENTRYPOINT = "{entrypoint}"


def main() -> None:
    # Kaggle runs a "T4 x2" kernel as TWO INDEPENDENT, namespace-isolated
    # processes/containers, not one process with two visible GPUs and not
    # two processes racing on a shared filesystem. Confirmed from a pulled
    # kernel log: both processes report the SAME PID (23) and produce
    # duplicated, deterministic output lines ~0.2s apart -- i.e. two
    # separate sandboxes that happen to reuse the same in-container PID,
    # with no shared state between them. There was never a real race on a
    # shared "/tmp/repo" clone directory (the garbage near-ceiling/chance
    # numbers seen earlier had a different cause). Naming this directory
    # per-PID therefore isn't required for correctness -- each process's
    # /tmp is already its own -- but it's harmless, so it's kept as-is.
    repo_dir = Path(f"/tmp/repo_{{os.getpid()}}")
    subprocess.run(["git", "clone", REPO_URL, str(repo_dir)], check=True)
    subprocess.run(["git", "-C", str(repo_dir), "checkout", REPO_COMMIT], check=True)
    # Install everything EXCEPT torch -- Kaggle's image ships a torch
    # build already validated against whatever GPU it hands out.
    # Reinstalling from our requirements.txt's loose "torch>=2.2" floor
    # pulled in a newer build with no compiled kernels for the GPU Kaggle
    # assigned in an earlier attempt (confirmed: "CUDA error: no kernel
    # image is available for execution on the device"). Keeping Kaggle's
    # preinstalled torch sidesteps this GPU-compute-capability-vs-wheel
    # problem entirely.
    all_reqs = (repo_dir / "requirements.txt").read_text().splitlines()
    reqs_without_torch = [line for line in all_reqs if not line.strip().lower().startswith("torch")]
    filtered_reqs_path = repo_dir / "requirements_kaggle.txt"
    filtered_reqs_path.write_text("\\n".join(reqs_without_torch))
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q", "-r", str(filtered_reqs_path)],
        check=True,
    )
    # No CUDA_VISIBLE_DEVICES override here: if Kaggle's own dual-process
    # launcher already assigns each of the two T4x2 processes its own GPU,
    # forcing both onto "0" would make them collide on one GPU (or break
    # whichever process didn't natively have a device 0). Let Kaggle's
    # own assignment stand.
    # PYTHONFAULTHANDLER: an earlier run crashed with no Python traceback
    # captured anywhere in the kernel log -- consistent with a native-level
    # crash (e.g. segfault) killing the process before normal exception
    # handling runs. faulthandler prints a low-level traceback on fatal
    # signals even then. PYTHONUNBUFFERED rules out output being lost to
    # buffering if the process dies abruptly.
    env = dict(os.environ, PYTHONFAULTHANDLER="1", PYTHONUNBUFFERED="1")
    subprocess.run([sys.executable, "-m", ENTRYPOINT], check=True, cwd=str(repo_dir), env=env)

    # Kaggle captures whatever's in the working directory as kernel output --
    # copy the entrypoint's results here explicitly rather than relying on
    # where it happened to write them relative to the cloned repo.
    for output_dir_name in ("calibration_output", "diagnostic_output"):
        src = repo_dir / "experiments" / output_dir_name
        if src.exists():
            shutil.copytree(src, output_dir_name, dirs_exist_ok=True)


if __name__ == "__main__":
    main()
'''


def render_kernel_script(repo_commit: str, entrypoint: str) -> str:
    """Fills in the Kaggle script-kernel template with a pinned commit and
    the module to run -- baked in as literals so the pushed kernel doesn't
    depend on Kaggle's environment-variable support."""
    return KERNEL_SCRIPT_TEMPLATE.format(repo_commit=repo_commit, entrypoint=entrypoint)


def render_kernel_notebook(repo_commit: str, entrypoint: str) -> str:
    """Wraps render_kernel_script()'s Python source into a minimal
    single-cell Jupyter notebook (nbformat 4). Same content, same
    reviewed logic as the script kernel -- this is only a different
    container format for Kaggle's notebook-kernel UI, not new logic
    living in a hand-edited notebook."""
    script = render_kernel_script(repo_commit, entrypoint)
    notebook = {
        "cells": [
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": script.splitlines(keepends=True),
            }
        ],
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    return json.dumps(notebook, indent=1)


def push(kernel_dir: Path, repo_commit: str, entrypoint: str) -> str:
    """Renders the kernel payload for (repo_commit, entrypoint) in
    whichever format kernel-metadata.json's code_file specifies (.py for
    a script kernel, .ipynb for a notebook kernel -- same underlying
    logic either way), writes it into kernel_dir, pushes via the kaggle
    CLI, and returns the kernel id read from kernel-metadata.json."""
    metadata = json.loads((kernel_dir / "kernel-metadata.json").read_text())
    code_file = kernel_dir / metadata["code_file"]
    if code_file.suffix == ".ipynb":
        content = render_kernel_notebook(repo_commit, entrypoint)
    else:
        content = render_kernel_script(repo_commit, entrypoint)
    code_file.write_text(content)
    subprocess.run(["kaggle", "kernels", "push", "-p", str(kernel_dir)], check=True)
    return metadata["id"]


def get_status(kernel_id: str) -> str:
    """Returns the kernel's current run status, normalized to a bare
    lowercase word ("running", "complete", "error", ...).

    Confirmed against the real CLI (2026-08-20): the raw quoted value is
    NOT a bare word as originally assumed -- it's an enum repr like
    `KernelWorkerStatus.RUNNING`, e.g. the full line is
    `{kernel_id} has status "KernelWorkerStatus.RUNNING"`. Strip the enum
    class prefix and lowercase it so callers (and TERMINAL_STATUSES) don't
    need to know about that wrapping."""
    result = subprocess.run(
        ["kaggle", "kernels", "status", kernel_id],
        check=True,
        capture_output=True,
        text=True,
    )
    raw_status = result.stdout.split('"')[1]
    return raw_status.rsplit(".", 1)[-1].lower()


def wait_for_completion(kernel_id: str, poll_interval_s: float = 30.0, timeout_s: float = 3600.0) -> str:
    """Polls get_status until it reaches a terminal status or timeout_s
    elapses. Returns the terminal status; raises TimeoutError on timeout."""
    start = time.monotonic()
    while True:
        status = get_status(kernel_id)
        if status in TERMINAL_STATUSES:
            return status
        if time.monotonic() - start > timeout_s:
            raise TimeoutError(
                f"kernel {kernel_id} did not finish within {timeout_s}s (last status: {status})"
            )
        time.sleep(poll_interval_s)


def pull_output(kernel_id: str, dest_dir: Path) -> Path:
    """Downloads the kernel's output files into dest_dir, returns dest_dir."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["kaggle", "kernels", "output", kernel_id, "-p", str(dest_dir)],
        check=True,
    )
    return dest_dir
